/*
 * generated by Xtext
 */
package fr.inria.aoste.timmo2use.tadl2.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class Tadl2ScopeProvider extends AbstractDeclarativeScopeProvider {

}
