/*
* generated by Xtext
*/
package fr.inria.aoste.timmo2use.tadl2.ui.contentassist;

import fr.inria.aoste.timmo2use.tadl2.ui.contentassist.AbstractTadl2ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Tadl2ProposalProvider extends AbstractTadl2ProposalProvider {

}
