/*
 * generated by Xtext
 */
package org.eclipse.gemoc.moccml.mapping.xtext.ui;

import org.eclipse.gemoc.moccml.mapping.xtext.ui.internal.EclActivator;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EclUiModule extends org.eclipse.gemoc.moccml.mapping.xtext.ui.AbstractEclUiModule {
	
	public static final String EDITOR_ID = EclActivator.ORG_ECLIPSE_GEMOC_MOCCML_MAPPING_XTEXT_ECL;

	public EclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
