/*
* generated by Xtext
*/
package fr.inria.aoste.timmo2use.tadl2.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.inria.aoste.timmo2use.tadl2.services.Tadl2GrammarAccess;

public class Tadl2Parser extends AbstractContentAssistParser {
	
	@Inject
	private Tadl2GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.inria.aoste.timmo2use.tadl2.ui.contentassist.antlr.internal.InternalTadl2Parser createParser() {
		fr.inria.aoste.timmo2use.tadl2.ui.contentassist.antlr.internal.InternalTadl2Parser result = new fr.inria.aoste.timmo2use.tadl2.ui.contentassist.antlr.internal.InternalTadl2Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTimingExpressionSpecificationAccess().getAlternatives_3(), "rule__TimingExpressionSpecification__Alternatives_3");
					put(grammarAccess.getTimingConstraintAccess().getAlternatives(), "rule__TimingConstraint__Alternatives");
					put(grammarAccess.getDelayConstraintAccess().getAlternatives_9(), "rule__DelayConstraint__Alternatives_9");
					put(grammarAccess.getDelayConstraintAccess().getAlternatives_12(), "rule__DelayConstraint__Alternatives_12");
					put(grammarAccess.getRepetitionConstraintAccess().getAlternatives_10(), "rule__RepetitionConstraint__Alternatives_10");
					put(grammarAccess.getRepetitionConstraintAccess().getAlternatives_13(), "rule__RepetitionConstraint__Alternatives_13");
					put(grammarAccess.getRepetitionConstraintAccess().getAlternatives_16(), "rule__RepetitionConstraint__Alternatives_16");
					put(grammarAccess.getSynchronizationConstraintAccess().getAlternatives_10(), "rule__SynchronizationConstraint__Alternatives_10");
					put(grammarAccess.getOrderConstraintAccess().getAlternatives_4(), "rule__OrderConstraint__Alternatives_4");
					put(grammarAccess.getOrderConstraintAccess().getAlternatives_6(), "rule__OrderConstraint__Alternatives_6");
					put(grammarAccess.getPatternConstraintAccess().getAlternatives(), "rule__PatternConstraint__Alternatives");
					put(grammarAccess.getPatternConstraintAccess().getAlternatives_0_9(), "rule__PatternConstraint__Alternatives_0_9");
					put(grammarAccess.getPatternConstraintAccess().getAlternatives_0_12(), "rule__PatternConstraint__Alternatives_0_12");
					put(grammarAccess.getPatternConstraintAccess().getAlternatives_1_1(), "rule__PatternConstraint__Alternatives_1_1");
					put(grammarAccess.getSporadicConstraintAccess().getAlternatives_7(), "rule__SporadicConstraint__Alternatives_7");
					put(grammarAccess.getSporadicConstraintAccess().getAlternatives_10(), "rule__SporadicConstraint__Alternatives_10");
					put(grammarAccess.getSporadicConstraintAccess().getAlternatives_13(), "rule__SporadicConstraint__Alternatives_13");
					put(grammarAccess.getSporadicConstraintAccess().getAlternatives_16(), "rule__SporadicConstraint__Alternatives_16");
					put(grammarAccess.getPeriodicConstraintAccess().getAlternatives_7(), "rule__PeriodicConstraint__Alternatives_7");
					put(grammarAccess.getPeriodicConstraintAccess().getAlternatives_10(), "rule__PeriodicConstraint__Alternatives_10");
					put(grammarAccess.getPeriodicConstraintAccess().getAlternatives_13(), "rule__PeriodicConstraint__Alternatives_13");
					put(grammarAccess.getArbitraryConstraintAccess().getAlternatives(), "rule__ArbitraryConstraint__Alternatives");
					put(grammarAccess.getArbitraryConstraintAccess().getAlternatives_1_1(), "rule__ArbitraryConstraint__Alternatives_1_1");
					put(grammarAccess.getArbitraryConstraintAccess().getAlternatives_2_1(), "rule__ArbitraryConstraint__Alternatives_2_1");
					put(grammarAccess.getBurstConstraintAccess().getAlternatives_10(), "rule__BurstConstraint__Alternatives_10");
					put(grammarAccess.getBurstConstraintAccess().getAlternatives_13(), "rule__BurstConstraint__Alternatives_13");
					put(grammarAccess.getReactionConstraintAccess().getAlternatives_7(), "rule__ReactionConstraint__Alternatives_7");
					put(grammarAccess.getReactionConstraintAccess().getAlternatives_10(), "rule__ReactionConstraint__Alternatives_10");
					put(grammarAccess.getAgeConstraintAccess().getAlternatives_7(), "rule__AgeConstraint__Alternatives_7");
					put(grammarAccess.getAgeConstraintAccess().getAlternatives_10(), "rule__AgeConstraint__Alternatives_10");
					put(grammarAccess.getTimingExpressionAccess().getAlternatives(), "rule__TimingExpression__Alternatives");
					put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
					put(grammarAccess.getSymbolicTimingExpressionAccess().getAlternatives(), "rule__SymbolicTimingExpression__Alternatives");
					put(grammarAccess.getVariableTimingExpressionAccess().getAlternatives_5_1(), "rule__VariableTimingExpression__Alternatives_5_1");
					put(grammarAccess.getValueTimingExpressionAccess().getAlternatives(), "rule__ValueTimingExpression__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTimeBaseRelationAccess().getAlternatives_3(), "rule__TimeBaseRelation__Alternatives_3");
					put(grammarAccess.getTimeBaseRelationAccess().getAlternatives_5(), "rule__TimeBaseRelation__Alternatives_5");
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getDimensionKindAccess().getAlternatives(), "rule__DimensionKind__Alternatives");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getGroup(), "rule__TimingExpressionSpecification__Group__0");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getGroup_3_0(), "rule__TimingExpressionSpecification__Group_3_0__0");
					put(grammarAccess.getImportStatementAccess().getGroup(), "rule__ImportStatement__Group__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getEventAccess().getGroup_4(), "rule__Event__Group_4__0");
					put(grammarAccess.getEventChainAccess().getGroup(), "rule__EventChain__Group__0");
					put(grammarAccess.getEventChainAccess().getGroup_7(), "rule__EventChain__Group_7__0");
					put(grammarAccess.getEventChainAccess().getGroup_7_2(), "rule__EventChain__Group_7_2__0");
					put(grammarAccess.getDelayConstraintAccess().getGroup(), "rule__DelayConstraint__Group__0");
					put(grammarAccess.getRepetitionConstraintAccess().getGroup(), "rule__RepetitionConstraint__Group__0");
					put(grammarAccess.getSynchronizationConstraintAccess().getGroup(), "rule__SynchronizationConstraint__Group__0");
					put(grammarAccess.getSynchronizationConstraintAccess().getGroup_7(), "rule__SynchronizationConstraint__Group_7__0");
					put(grammarAccess.getOrderConstraintAccess().getGroup(), "rule__OrderConstraint__Group__0");
					put(grammarAccess.getPatternConstraintAccess().getGroup_0(), "rule__PatternConstraint__Group_0__0");
					put(grammarAccess.getPatternConstraintAccess().getGroup_1(), "rule__PatternConstraint__Group_1__0");
					put(grammarAccess.getPatternConstraintAccess().getGroup_1_1_0(), "rule__PatternConstraint__Group_1_1_0__0");
					put(grammarAccess.getSporadicConstraintAccess().getGroup(), "rule__SporadicConstraint__Group__0");
					put(grammarAccess.getPeriodicConstraintAccess().getGroup(), "rule__PeriodicConstraint__Group__0");
					put(grammarAccess.getArbitraryConstraintAccess().getGroup_0(), "rule__ArbitraryConstraint__Group_0__0");
					put(grammarAccess.getArbitraryConstraintAccess().getGroup_1(), "rule__ArbitraryConstraint__Group_1__0");
					put(grammarAccess.getArbitraryConstraintAccess().getGroup_1_1_0(), "rule__ArbitraryConstraint__Group_1_1_0__0");
					put(grammarAccess.getArbitraryConstraintAccess().getGroup_2(), "rule__ArbitraryConstraint__Group_2__0");
					put(grammarAccess.getArbitraryConstraintAccess().getGroup_2_1_0(), "rule__ArbitraryConstraint__Group_2_1_0__0");
					put(grammarAccess.getBurstConstraintAccess().getGroup(), "rule__BurstConstraint__Group__0");
					put(grammarAccess.getReactionConstraintAccess().getGroup(), "rule__ReactionConstraint__Group__0");
					put(grammarAccess.getAgeConstraintAccess().getGroup(), "rule__AgeConstraint__Group__0");
					put(grammarAccess.getAdditionAccess().getGroup(), "rule__Addition__Group__0");
					put(grammarAccess.getSymbolicTimingExpressionAccess().getGroup_0(), "rule__SymbolicTimingExpression__Group_0__0");
					put(grammarAccess.getVariableTimingExpressionAccess().getGroup(), "rule__VariableTimingExpression__Group__0");
					put(grammarAccess.getVariableTimingExpressionAccess().getGroup_5(), "rule__VariableTimingExpression__Group_5__0");
					put(grammarAccess.getValueTimingExpressionAccess().getGroup_0(), "rule__ValueTimingExpression__Group_0__0");
					put(grammarAccess.getValueTimingExpressionAccess().getGroup_0_3(), "rule__ValueTimingExpression__Group_0_3__0");
					put(grammarAccess.getSubtractionAccess().getGroup(), "rule__Subtraction__Group__0");
					put(grammarAccess.getMultiplicationAccess().getGroup(), "rule__Multiplication__Group__0");
					put(grammarAccess.getDivisionAccess().getGroup(), "rule__Division__Group__0");
					put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
					put(grammarAccess.getGreaterThanAccess().getGroup(), "rule__GreaterThan__Group__0");
					put(grammarAccess.getLessThanAccess().getGroup(), "rule__LessThan__Group__0");
					put(grammarAccess.getGreaterThanOrEqualAccess().getGroup(), "rule__GreaterThanOrEqual__Group__0");
					put(grammarAccess.getLessThanOrEqualAccess().getGroup(), "rule__LessThanOrEqual__Group__0");
					put(grammarAccess.getTimeBaseAccess().getGroup(), "rule__TimeBase__Group__0");
					put(grammarAccess.getTimeBaseAccess().getGroup_5(), "rule__TimeBase__Group_5__0");
					put(grammarAccess.getTimeBaseAccess().getGroup_6(), "rule__TimeBase__Group_6__0");
					put(grammarAccess.getUnitAccess().getGroup(), "rule__Unit__Group__0");
					put(grammarAccess.getUnitAccess().getGroup_3(), "rule__Unit__Group_3__0");
					put(grammarAccess.getUnitAccess().getGroup_4(), "rule__Unit__Group_4__0");
					put(grammarAccess.getUnitAccess().getGroup_5(), "rule__Unit__Group_5__0");
					put(grammarAccess.getDimensionAccess().getGroup(), "rule__Dimension__Group__0");
					put(grammarAccess.getDimensionAccess().getGroup_3(), "rule__Dimension__Group_3__0");
					put(grammarAccess.getDimensionAccess().getGroup_7(), "rule__Dimension__Group_7__0");
					put(grammarAccess.getTimeBaseRelationAccess().getGroup(), "rule__TimeBaseRelation__Group__0");
					put(grammarAccess.getTimeBaseRelationAccess().getGroup_3_1(), "rule__TimeBaseRelation__Group_3_1__0");
					put(grammarAccess.getTimeBaseRelationAccess().getGroup_5_1(), "rule__TimeBaseRelation__Group_5_1__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getNameAssignment_1(), "rule__TimingExpressionSpecification__NameAssignment_1");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getTimingExpressionsAssignment_3_0_1(), "rule__TimingExpressionSpecification__TimingExpressionsAssignment_3_0_1");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getImportStatementsAssignment_3_1(), "rule__TimingExpressionSpecification__ImportStatementsAssignment_3_1");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getEventsAssignment_3_2(), "rule__TimingExpressionSpecification__EventsAssignment_3_2");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getEventChainsAssignment_3_3(), "rule__TimingExpressionSpecification__EventChainsAssignment_3_3");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getConstraintsAssignment_3_4(), "rule__TimingExpressionSpecification__ConstraintsAssignment_3_4");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getTimingExpressionsAssignment_3_5(), "rule__TimingExpressionSpecification__TimingExpressionsAssignment_3_5");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getTimeBasesAssignment_3_6(), "rule__TimingExpressionSpecification__TimeBasesAssignment_3_6");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getDimensionsAssignment_3_7(), "rule__TimingExpressionSpecification__DimensionsAssignment_3_7");
					put(grammarAccess.getTimingExpressionSpecificationAccess().getTimeBaseRelationsAssignment_3_8(), "rule__TimingExpressionSpecification__TimeBaseRelationsAssignment_3_8");
					put(grammarAccess.getImportStatementAccess().getImportURIAssignment_1(), "rule__ImportStatement__ImportURIAssignment_1");
					put(grammarAccess.getImportStatementAccess().getAliasAssignment_3(), "rule__ImportStatement__AliasAssignment_3");
					put(grammarAccess.getEventAccess().getNameAssignment_1(), "rule__Event__NameAssignment_1");
					put(grammarAccess.getEventAccess().getTriggerableElementsAssignment_3(), "rule__Event__TriggerableElementsAssignment_3");
					put(grammarAccess.getEventAccess().getTriggerableElementsAssignment_4_1(), "rule__Event__TriggerableElementsAssignment_4_1");
					put(grammarAccess.getEventChainAccess().getNameAssignment_1(), "rule__EventChain__NameAssignment_1");
					put(grammarAccess.getEventChainAccess().getStimulusAssignment_4(), "rule__EventChain__StimulusAssignment_4");
					put(grammarAccess.getEventChainAccess().getResponseAssignment_6(), "rule__EventChain__ResponseAssignment_6");
					put(grammarAccess.getEventChainAccess().getSegmentAssignment_7_1(), "rule__EventChain__SegmentAssignment_7_1");
					put(grammarAccess.getEventChainAccess().getSegmentAssignment_7_2_1(), "rule__EventChain__SegmentAssignment_7_2_1");
					put(grammarAccess.getDelayConstraintAccess().getNameAssignment_1(), "rule__DelayConstraint__NameAssignment_1");
					put(grammarAccess.getDelayConstraintAccess().getSourceAssignment_4(), "rule__DelayConstraint__SourceAssignment_4");
					put(grammarAccess.getDelayConstraintAccess().getTargetAssignment_6(), "rule__DelayConstraint__TargetAssignment_6");
					put(grammarAccess.getDelayConstraintAccess().getLowerAssignment_9_0(), "rule__DelayConstraint__LowerAssignment_9_0");
					put(grammarAccess.getDelayConstraintAccess().getLowerAssignment_9_1(), "rule__DelayConstraint__LowerAssignment_9_1");
					put(grammarAccess.getDelayConstraintAccess().getUpperAssignment_12_0(), "rule__DelayConstraint__UpperAssignment_12_0");
					put(grammarAccess.getDelayConstraintAccess().getUpperAssignment_12_1(), "rule__DelayConstraint__UpperAssignment_12_1");
					put(grammarAccess.getRepetitionConstraintAccess().getNameAssignment_1(), "rule__RepetitionConstraint__NameAssignment_1");
					put(grammarAccess.getRepetitionConstraintAccess().getEventAssignment_4(), "rule__RepetitionConstraint__EventAssignment_4");
					put(grammarAccess.getRepetitionConstraintAccess().getSpanAssignment_7(), "rule__RepetitionConstraint__SpanAssignment_7");
					put(grammarAccess.getRepetitionConstraintAccess().getLowerAssignment_10_0(), "rule__RepetitionConstraint__LowerAssignment_10_0");
					put(grammarAccess.getRepetitionConstraintAccess().getLowerAssignment_10_1(), "rule__RepetitionConstraint__LowerAssignment_10_1");
					put(grammarAccess.getRepetitionConstraintAccess().getUpperAssignment_13_0(), "rule__RepetitionConstraint__UpperAssignment_13_0");
					put(grammarAccess.getRepetitionConstraintAccess().getUpperAssignment_13_1(), "rule__RepetitionConstraint__UpperAssignment_13_1");
					put(grammarAccess.getRepetitionConstraintAccess().getJitterAssignment_16_0(), "rule__RepetitionConstraint__JitterAssignment_16_0");
					put(grammarAccess.getRepetitionConstraintAccess().getJitterAssignment_16_1(), "rule__RepetitionConstraint__JitterAssignment_16_1");
					put(grammarAccess.getSynchronizationConstraintAccess().getNameAssignment_1(), "rule__SynchronizationConstraint__NameAssignment_1");
					put(grammarAccess.getSynchronizationConstraintAccess().getEventsAssignment_4(), "rule__SynchronizationConstraint__EventsAssignment_4");
					put(grammarAccess.getSynchronizationConstraintAccess().getEventsAssignment_6(), "rule__SynchronizationConstraint__EventsAssignment_6");
					put(grammarAccess.getSynchronizationConstraintAccess().getEventsAssignment_7_1(), "rule__SynchronizationConstraint__EventsAssignment_7_1");
					put(grammarAccess.getSynchronizationConstraintAccess().getToleranceAssignment_10_0(), "rule__SynchronizationConstraint__ToleranceAssignment_10_0");
					put(grammarAccess.getSynchronizationConstraintAccess().getToleranceAssignment_10_1(), "rule__SynchronizationConstraint__ToleranceAssignment_10_1");
					put(grammarAccess.getOrderConstraintAccess().getNameAssignment_1(), "rule__OrderConstraint__NameAssignment_1");
					put(grammarAccess.getOrderConstraintAccess().getLeftAssignment_4_0(), "rule__OrderConstraint__LeftAssignment_4_0");
					put(grammarAccess.getOrderConstraintAccess().getLeftAssignment_4_1(), "rule__OrderConstraint__LeftAssignment_4_1");
					put(grammarAccess.getOrderConstraintAccess().getRightAssignment_6_0(), "rule__OrderConstraint__RightAssignment_6_0");
					put(grammarAccess.getOrderConstraintAccess().getRightAssignment_6_1(), "rule__OrderConstraint__RightAssignment_6_1");
					put(grammarAccess.getPatternConstraintAccess().getNameAssignment_0_1(), "rule__PatternConstraint__NameAssignment_0_1");
					put(grammarAccess.getPatternConstraintAccess().getEventAssignment_0_4(), "rule__PatternConstraint__EventAssignment_0_4");
					put(grammarAccess.getPatternConstraintAccess().getRefAssignment_0_6(), "rule__PatternConstraint__RefAssignment_0_6");
					put(grammarAccess.getPatternConstraintAccess().getMinimumAssignment_0_9_0(), "rule__PatternConstraint__MinimumAssignment_0_9_0");
					put(grammarAccess.getPatternConstraintAccess().getMinimumAssignment_0_9_1(), "rule__PatternConstraint__MinimumAssignment_0_9_1");
					put(grammarAccess.getPatternConstraintAccess().getJitterAssignment_0_12_0(), "rule__PatternConstraint__JitterAssignment_0_12_0");
					put(grammarAccess.getPatternConstraintAccess().getJitterAssignment_0_12_1(), "rule__PatternConstraint__JitterAssignment_0_12_1");
					put(grammarAccess.getPatternConstraintAccess().getOffsetAssignment_0_15(), "rule__PatternConstraint__OffsetAssignment_0_15");
					put(grammarAccess.getPatternConstraintAccess().getOffsetAssignment_1_0(), "rule__PatternConstraint__OffsetAssignment_1_0");
					put(grammarAccess.getPatternConstraintAccess().getOffsetAssignment_1_1_0_1(), "rule__PatternConstraint__OffsetAssignment_1_1_0_1");
					put(grammarAccess.getPatternConstraintAccess().getOffsetAssignment_1_1_1(), "rule__PatternConstraint__OffsetAssignment_1_1_1");
					put(grammarAccess.getSporadicConstraintAccess().getNameAssignment_1(), "rule__SporadicConstraint__NameAssignment_1");
					put(grammarAccess.getSporadicConstraintAccess().getEventAssignment_4(), "rule__SporadicConstraint__EventAssignment_4");
					put(grammarAccess.getSporadicConstraintAccess().getLowerAssignment_7_0(), "rule__SporadicConstraint__LowerAssignment_7_0");
					put(grammarAccess.getSporadicConstraintAccess().getLowerAssignment_7_1(), "rule__SporadicConstraint__LowerAssignment_7_1");
					put(grammarAccess.getSporadicConstraintAccess().getUpperAssignment_10_0(), "rule__SporadicConstraint__UpperAssignment_10_0");
					put(grammarAccess.getSporadicConstraintAccess().getUpperAssignment_10_1(), "rule__SporadicConstraint__UpperAssignment_10_1");
					put(grammarAccess.getSporadicConstraintAccess().getJitterAssignment_13_0(), "rule__SporadicConstraint__JitterAssignment_13_0");
					put(grammarAccess.getSporadicConstraintAccess().getJitterAssignment_13_1(), "rule__SporadicConstraint__JitterAssignment_13_1");
					put(grammarAccess.getSporadicConstraintAccess().getMinimumAssignment_16_0(), "rule__SporadicConstraint__MinimumAssignment_16_0");
					put(grammarAccess.getSporadicConstraintAccess().getMinimumAssignment_16_1(), "rule__SporadicConstraint__MinimumAssignment_16_1");
					put(grammarAccess.getPeriodicConstraintAccess().getNameAssignment_1(), "rule__PeriodicConstraint__NameAssignment_1");
					put(grammarAccess.getPeriodicConstraintAccess().getEventAssignment_4(), "rule__PeriodicConstraint__EventAssignment_4");
					put(grammarAccess.getPeriodicConstraintAccess().getPeriodAssignment_7_0(), "rule__PeriodicConstraint__PeriodAssignment_7_0");
					put(grammarAccess.getPeriodicConstraintAccess().getPeriodAssignment_7_1(), "rule__PeriodicConstraint__PeriodAssignment_7_1");
					put(grammarAccess.getPeriodicConstraintAccess().getMinimumAssignment_10_0(), "rule__PeriodicConstraint__MinimumAssignment_10_0");
					put(grammarAccess.getPeriodicConstraintAccess().getMinimumAssignment_10_1(), "rule__PeriodicConstraint__MinimumAssignment_10_1");
					put(grammarAccess.getPeriodicConstraintAccess().getJitterAssignment_13_0(), "rule__PeriodicConstraint__JitterAssignment_13_0");
					put(grammarAccess.getPeriodicConstraintAccess().getJitterAssignment_13_1(), "rule__PeriodicConstraint__JitterAssignment_13_1");
					put(grammarAccess.getArbitraryConstraintAccess().getNameAssignment_0_1(), "rule__ArbitraryConstraint__NameAssignment_0_1");
					put(grammarAccess.getArbitraryConstraintAccess().getEventAssignment_0_4(), "rule__ArbitraryConstraint__EventAssignment_0_4");
					put(grammarAccess.getArbitraryConstraintAccess().getMinimumAssignment_0_7(), "rule__ArbitraryConstraint__MinimumAssignment_0_7");
					put(grammarAccess.getArbitraryConstraintAccess().getMinimumAssignment_1_0(), "rule__ArbitraryConstraint__MinimumAssignment_1_0");
					put(grammarAccess.getArbitraryConstraintAccess().getMinimumAssignment_1_1_0_1(), "rule__ArbitraryConstraint__MinimumAssignment_1_1_0_1");
					put(grammarAccess.getArbitraryConstraintAccess().getMinimumAssignment_1_1_1(), "rule__ArbitraryConstraint__MinimumAssignment_1_1_1");
					put(grammarAccess.getArbitraryConstraintAccess().getMaximumAssignment_1_4(), "rule__ArbitraryConstraint__MaximumAssignment_1_4");
					put(grammarAccess.getArbitraryConstraintAccess().getMaximumAssignment_2_0(), "rule__ArbitraryConstraint__MaximumAssignment_2_0");
					put(grammarAccess.getArbitraryConstraintAccess().getMaximumAssignment_2_1_0_1(), "rule__ArbitraryConstraint__MaximumAssignment_2_1_0_1");
					put(grammarAccess.getArbitraryConstraintAccess().getMaximumAssignment_2_1_1(), "rule__ArbitraryConstraint__MaximumAssignment_2_1_1");
					put(grammarAccess.getBurstConstraintAccess().getNameAssignment_1(), "rule__BurstConstraint__NameAssignment_1");
					put(grammarAccess.getBurstConstraintAccess().getEventAssignment_4(), "rule__BurstConstraint__EventAssignment_4");
					put(grammarAccess.getBurstConstraintAccess().getMaxOccurrenceAssignment_7(), "rule__BurstConstraint__MaxOccurrenceAssignment_7");
					put(grammarAccess.getBurstConstraintAccess().getLengthAssignment_10_0(), "rule__BurstConstraint__LengthAssignment_10_0");
					put(grammarAccess.getBurstConstraintAccess().getLengthAssignment_10_1(), "rule__BurstConstraint__LengthAssignment_10_1");
					put(grammarAccess.getBurstConstraintAccess().getMinimumAssignment_13_0(), "rule__BurstConstraint__MinimumAssignment_13_0");
					put(grammarAccess.getBurstConstraintAccess().getMinimumAssignment_13_1(), "rule__BurstConstraint__MinimumAssignment_13_1");
					put(grammarAccess.getReactionConstraintAccess().getNameAssignment_1(), "rule__ReactionConstraint__NameAssignment_1");
					put(grammarAccess.getReactionConstraintAccess().getScopeAssignment_4(), "rule__ReactionConstraint__ScopeAssignment_4");
					put(grammarAccess.getReactionConstraintAccess().getMaximumAssignment_7_0(), "rule__ReactionConstraint__MaximumAssignment_7_0");
					put(grammarAccess.getReactionConstraintAccess().getMaximumAssignment_7_1(), "rule__ReactionConstraint__MaximumAssignment_7_1");
					put(grammarAccess.getReactionConstraintAccess().getMinimumAssignment_10_0(), "rule__ReactionConstraint__MinimumAssignment_10_0");
					put(grammarAccess.getReactionConstraintAccess().getMinimumAssignment_10_1(), "rule__ReactionConstraint__MinimumAssignment_10_1");
					put(grammarAccess.getAgeConstraintAccess().getNameAssignment_1(), "rule__AgeConstraint__NameAssignment_1");
					put(grammarAccess.getAgeConstraintAccess().getScopeAssignment_4(), "rule__AgeConstraint__ScopeAssignment_4");
					put(grammarAccess.getAgeConstraintAccess().getMaximumAssignment_7_0(), "rule__AgeConstraint__MaximumAssignment_7_0");
					put(grammarAccess.getAgeConstraintAccess().getMaximumAssignment_7_1(), "rule__AgeConstraint__MaximumAssignment_7_1");
					put(grammarAccess.getAgeConstraintAccess().getMinimumAssignment_10_0(), "rule__AgeConstraint__MinimumAssignment_10_0");
					put(grammarAccess.getAgeConstraintAccess().getMinimumAssignment_10_1(), "rule__AgeConstraint__MinimumAssignment_10_1");
					put(grammarAccess.getAdditionAccess().getLeftOperandAssignment_1(), "rule__Addition__LeftOperandAssignment_1");
					put(grammarAccess.getAdditionAccess().getRightOperandAssignment_3(), "rule__Addition__RightOperandAssignment_3");
					put(grammarAccess.getSymbolicTimingExpressionAccess().getVariableAssignment_0_1(), "rule__SymbolicTimingExpression__VariableAssignment_0_1");
					put(grammarAccess.getSymbolicTimingExpressionAccess().getOperatorAssignment_1(), "rule__SymbolicTimingExpression__OperatorAssignment_1");
					put(grammarAccess.getVariableTimingExpressionAccess().getNameAssignment_1(), "rule__VariableTimingExpression__NameAssignment_1");
					put(grammarAccess.getVariableTimingExpressionAccess().getUnitAssignment_2(), "rule__VariableTimingExpression__UnitAssignment_2");
					put(grammarAccess.getVariableTimingExpressionAccess().getTimeBaseAssignment_4(), "rule__VariableTimingExpression__TimeBaseAssignment_4");
					put(grammarAccess.getVariableTimingExpressionAccess().getValueAssignment_5_1_0(), "rule__VariableTimingExpression__ValueAssignment_5_1_0");
					put(grammarAccess.getVariableTimingExpressionAccess().getValueAssignment_5_1_1(), "rule__VariableTimingExpression__ValueAssignment_5_1_1");
					put(grammarAccess.getValueTimingExpressionAccess().getValueAssignment_0_1(), "rule__ValueTimingExpression__ValueAssignment_0_1");
					put(grammarAccess.getValueTimingExpressionAccess().getUnitAssignment_0_2(), "rule__ValueTimingExpression__UnitAssignment_0_2");
					put(grammarAccess.getValueTimingExpressionAccess().getTimeBaseAssignment_0_3_1(), "rule__ValueTimingExpression__TimeBaseAssignment_0_3_1");
					put(grammarAccess.getValueTimingExpressionAccess().getValueAssignment_1(), "rule__ValueTimingExpression__ValueAssignment_1");
					put(grammarAccess.getSubtractionAccess().getLeftOperandAssignment_1(), "rule__Subtraction__LeftOperandAssignment_1");
					put(grammarAccess.getSubtractionAccess().getRightOperandAssignment_3(), "rule__Subtraction__RightOperandAssignment_3");
					put(grammarAccess.getMultiplicationAccess().getLeftOperandAssignment_1(), "rule__Multiplication__LeftOperandAssignment_1");
					put(grammarAccess.getMultiplicationAccess().getRightOperandAssignment_3(), "rule__Multiplication__RightOperandAssignment_3");
					put(grammarAccess.getDivisionAccess().getLeftOperandAssignment_1(), "rule__Division__LeftOperandAssignment_1");
					put(grammarAccess.getDivisionAccess().getRightOperandAssignment_3(), "rule__Division__RightOperandAssignment_3");
					put(grammarAccess.getAssignmentAccess().getLeftOperandAssignment_1(), "rule__Assignment__LeftOperandAssignment_1");
					put(grammarAccess.getAssignmentAccess().getRightOperandAssignment_3(), "rule__Assignment__RightOperandAssignment_3");
					put(grammarAccess.getGreaterThanAccess().getLeftOperandAssignment_1(), "rule__GreaterThan__LeftOperandAssignment_1");
					put(grammarAccess.getGreaterThanAccess().getRightOperandAssignment_3(), "rule__GreaterThan__RightOperandAssignment_3");
					put(grammarAccess.getLessThanAccess().getLeftOperandAssignment_1(), "rule__LessThan__LeftOperandAssignment_1");
					put(grammarAccess.getLessThanAccess().getRightOperandAssignment_3(), "rule__LessThan__RightOperandAssignment_3");
					put(grammarAccess.getGreaterThanOrEqualAccess().getLeftOperandAssignment_1(), "rule__GreaterThanOrEqual__LeftOperandAssignment_1");
					put(grammarAccess.getGreaterThanOrEqualAccess().getRightOperandAssignment_3(), "rule__GreaterThanOrEqual__RightOperandAssignment_3");
					put(grammarAccess.getLessThanOrEqualAccess().getLeftOperandAssignment_1(), "rule__LessThanOrEqual__LeftOperandAssignment_1");
					put(grammarAccess.getLessThanOrEqualAccess().getRightOperandAssignment_3(), "rule__LessThanOrEqual__RightOperandAssignment_3");
					put(grammarAccess.getTimeBaseAccess().getNameAssignment_1(), "rule__TimeBase__NameAssignment_1");
					put(grammarAccess.getTimeBaseAccess().getTypeAssignment_4(), "rule__TimeBase__TypeAssignment_4");
					put(grammarAccess.getTimeBaseAccess().getPrecisionFactorAssignment_5_1(), "rule__TimeBase__PrecisionFactorAssignment_5_1");
					put(grammarAccess.getTimeBaseAccess().getPrecisionUnitAssignment_6_1(), "rule__TimeBase__PrecisionUnitAssignment_6_1");
					put(grammarAccess.getUnitAccess().getNameAssignment_1(), "rule__Unit__NameAssignment_1");
					put(grammarAccess.getUnitAccess().getFactorAssignment_3_1(), "rule__Unit__FactorAssignment_3_1");
					put(grammarAccess.getUnitAccess().getOffsetAssignment_4_1(), "rule__Unit__OffsetAssignment_4_1");
					put(grammarAccess.getUnitAccess().getReferenceAssignment_5_1(), "rule__Unit__ReferenceAssignment_5_1");
					put(grammarAccess.getDimensionAccess().getNameAssignment_1(), "rule__Dimension__NameAssignment_1");
					put(grammarAccess.getDimensionAccess().getKindAssignment_3_1(), "rule__Dimension__KindAssignment_3_1");
					put(grammarAccess.getDimensionAccess().getUnitsAssignment_6(), "rule__Dimension__UnitsAssignment_6");
					put(grammarAccess.getDimensionAccess().getUnitsAssignment_7_1(), "rule__Dimension__UnitsAssignment_7_1");
					put(grammarAccess.getTimeBaseRelationAccess().getNameAssignment_1(), "rule__TimeBaseRelation__NameAssignment_1");
					put(grammarAccess.getTimeBaseRelationAccess().getLeftAssignment_3_0(), "rule__TimeBaseRelation__LeftAssignment_3_0");
					put(grammarAccess.getTimeBaseRelationAccess().getLeftAssignment_3_1_1(), "rule__TimeBaseRelation__LeftAssignment_3_1_1");
					put(grammarAccess.getTimeBaseRelationAccess().getLeftAssignment_3_2(), "rule__TimeBaseRelation__LeftAssignment_3_2");
					put(grammarAccess.getTimeBaseRelationAccess().getRightAssignment_5_0(), "rule__TimeBaseRelation__RightAssignment_5_0");
					put(grammarAccess.getTimeBaseRelationAccess().getRightAssignment_5_1_1(), "rule__TimeBaseRelation__RightAssignment_5_1_1");
					put(grammarAccess.getTimeBaseRelationAccess().getRightAssignment_5_2(), "rule__TimeBaseRelation__RightAssignment_5_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.inria.aoste.timmo2use.tadl2.ui.contentassist.antlr.internal.InternalTadl2Parser typedParser = (fr.inria.aoste.timmo2use.tadl2.ui.contentassist.antlr.internal.InternalTadl2Parser) parser;
			typedParser.entryRuleTimingExpressionSpecification();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Tadl2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Tadl2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
