/*
* generated by Xtext
*/
package fr.inria.aoste.timmo2use.tadl2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Tadl2AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/aoste/timmo2use/tadl2/parser/antlr/internal/InternalTadl2.tokens");
	}
}
