/*
* generated by Xtext
*/
package fr.inria.aoste.timmo2use.tadl2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.aoste.timmo2use.tadl2.services.Tadl2GrammarAccess;

public class Tadl2Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Tadl2GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.aoste.timmo2use.tadl2.parser.antlr.internal.InternalTadl2Parser createParser(XtextTokenStream stream) {
		return new fr.inria.aoste.timmo2use.tadl2.parser.antlr.internal.InternalTadl2Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TimingExpressionSpecification";
	}
	
	public Tadl2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Tadl2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
