/*
* generated by Xtext
*/
package org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FSMDslStandaloneSetup extends FSMDslStandaloneSetupGenerated{

	public static void doSetup() {
		new FSMDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

