/*
* generated by Xtext
*/
package fr.inria.aoste.timmo2use.tadl2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class Tadl2OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
