/*
 * generated by Xtext
 */
package org.eclipse.gemoc.moccml.mapping.xtext.scoping;

import org.eclipse.ocl.xtext.completeocl.scoping.CompleteOCLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class EclScopeProvider extends CompleteOCLScopeProvider{//AbstractDeclarativeScopeProvider {
	
//	//CompleteOCLScopeProvider delegator = new CompleteOCLScopeProvider();
//	
//	@Override
//	public IScope getScope(EObject context, EReference reference) {
////		if (context instanceof Relation | context instanceof ECLExpression){
////			return super.getScope(context, reference);
////		}
////		else{
//			return super.getScope(context, reference);
////		}
//		
//	}
}
