/*
* generated by Xtext
*/
package org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class MoCDslProposalProvider extends org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.ui.contentassist.AbstractMoCDslProposalProvider {

}
