/*
* generated by Xtext
*/
package org.eclipse.gemoc.moccml.mapping.xtext.ui.outline;

import org.eclipse.ocl.xtext.completeocl.ui.outline.CompleteOCLOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EclOutlineTreeProvider extends CompleteOCLOutlineTreeProvider {
	
}
