/*
 * generated by Xtext
 */
package fr.inria.aoste.timmo2use.tadl2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Tadl2UiModule extends fr.inria.aoste.timmo2use.tadl2.ui.AbstractTadl2UiModule {
	public Tadl2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
