<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tadl2" nsURI="http://fr.inria.aoste.timmo2use.tadl2" nsPrefix="fr.inria.aoste.timmo2use.tadl2">
  <eSubpackages name="TimingExpressions" nsURI="http://fr.inria.aoste.timmo2use.tadl2.TimingExpressions"
      nsPrefix="fr.inria.aoste.timmo2use.tadl2">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimingExpression" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SymbolicTimingExpression" eSuperTypes="#//TimingExpressions/TimingExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//TimingExpressions/Operator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//TimingExpressions/VariableTimingExpression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableTimingExpression" eSuperTypes="#//TimingExpressions/TimingExpression #//TimingExpressions/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TimingExpressions/TimingExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeBase" lowerBound="1"
          eType="#//TimingExpressions/TimeBase"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1"
          eType="#//TimingExpressions/Unit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="Subtraction" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="ValueTimingExpression" eSuperTypes="#//TimingExpressions/TimingExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeBase" eType="#//TimingExpressions/TimeBase"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//TimingExpressions/Unit"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeBase" eSuperTypes="#//TimingExpressions/NamedElement">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="units"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//TimingExpressions/Dimension">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="precisionUnit" eType="#//TimingExpressions/Unit">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precisionFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dimension" eSuperTypes="#//TimingExpressions/NamedElement">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="units"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="units" lowerBound="1"
          upperBound="-1" eType="#//TimingExpressions/Unit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//TimingExpressions/DimensionKind">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//TimingExpressions/NamedElement">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="units"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//TimingExpressions/Unit">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="units"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DimensionKind">
      <eLiterals name="other"/>
      <eLiterals name="Time" value="1"/>
      <eLiterals name="Angle" value="2"/>
      <eLiterals name="Distance" value="3"/>
      <eLiterals name="Logical" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeBaseRelation" eSuperTypes="#//TimingExpressions/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Timing" eSuperTypes="#//TimingExpressions/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="timingExpressions" upperBound="-1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeBases" upperBound="-1"
          eType="#//TimingExpressions/TimeBase" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
          eType="#//TimingExpressions/Dimension" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeBaseRelations" upperBound="-1"
          eType="#//TimingExpressions/TimeBaseRelation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
          eType="#//TimingExpressions/Event" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//TimingExpressions/TimingConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventChains" upperBound="-1"
          eType="#//TimingExpressions/EventChain" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="importStatements" upperBound="-1"
          eType="#//TimingExpressions/ImportStatement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterThan" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterThanOrEqual" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="LessThan" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="LessThanOrEqual" eSuperTypes="#//TimingExpressions/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimingConstraint" abstract="true"
        eSuperTypes="#//TimingExpressions/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DelayConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lower" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upper" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RepetitionConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lower" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upper" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jitter" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SynchronizationConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" lowerBound="2"
          upperBound="-1" eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tolerance" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//TimingExpressions/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="triggerableElements"
          upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PatternConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="offset" lowerBound="1"
          upperBound="-1" eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jitter" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SporadicConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lower" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upper" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jitter" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PeriodicConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="period" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jitter" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArbitraryConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          upperBound="-1" eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" lowerBound="1"
          upperBound="-1" eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BurstConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurrence" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReactionConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1"
          eType="#//TimingExpressions/EventChain"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AgeConstraint" eSuperTypes="#//TimingExpressions/TimingConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" lowerBound="1"
          eType="#//TimingExpressions/TimingExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1"
          eType="#//TimingExpressions/EventChain"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventChain" eSuperTypes="#//TimingExpressions/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stimulus" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="response" lowerBound="1"
          eType="#//TimingExpressions/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="segment" upperBound="-1"
          eType="#//TimingExpressions/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImportStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
