<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="concurrent_xdsml_with_gel" nsURI="http://www.gemoc.org/concurrent_xdsml_with_gel"
    nsPrefix="concurrent_xdsml_with_gel">
  <eClassifiers xsi:type="ecore:EClass" name="ConcurrentLanguageWithGelDefinition"
      eSuperTypes="../../org.gemoc.executionengine.ccsljava.concurrent_xdsml.model/model/concurrent_xdsml.ecore#//ConcurrentLanguageDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="GelProject" eSuperTypes="../../org.gemoc.executionframework.xdsml_base.model/model/xdsml_base.ecore#//ProjectResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GelSpecificationURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
