<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eastLight" nsURI="http://fr.inria.aoste.gemoc.eastadl" nsPrefix="eastLight">
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisFunctionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionTrigger" ordered="false"
        eType="#//FunctionTrigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerCondition" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="TODO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" ordered="false" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerPolicyKind" ordered="false"
        lowerBound="1" eType="#//TriggerPolicyKind" defaultValueLiteral="EVENT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerPolicyKind">
    <eLiterals name="EVENT"/>
    <eLiterals name="TIME" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisFunctionPrototype">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionTrigger" ordered="false"
        eType="#//FunctionTrigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false"
        lowerBound="1" eType="#//PortDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PortDirection">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
  </eClassifiers>
</ecore:EPackage>
